### ISSUE TITLE
Shortcut for "font master bundle"

### ISSUE THREAD

**Issue by darshan06** [keremciu/sketch-iconfont#155]
Hello, 
I am fan of iconfont plugin and its in my daily use, but I want to set keyboard Shortcut cut for the iconfont master bundle fonts how can I do that? for example (ctrl+cmd+M) will open material icon screen.
I install another font and that allow me to set shortcut but the font master bundle having no option to set keyboard shortcut ( If it has please explain me how to set).

Thank You team iconfont.

**Comment by mamuts12** [comment]
By Default The Shortcut for the fonts are cmd+ctrl+f but since there multiple fonts that won't work

Since i only use certain fonts i did this
Opened Sketch Plugins folder -> Opened icon package content -> found manifest.json and changed the certain font shortcut keys

![img](https://user-images.githubusercontent.com/17852229/54696239-299c4300-4b34-11e9-8eb7-edaba7de6442.png)

**Comment by darshan06** [comment]
> By Default The Shortcut for the fonts are cmd+ctrl+f but since there are multiple fonts, that won't work
> 
> Because I only use certain fonts I did this
> Open Sketch Plugins folder -> Open icon package content -> find manifest.json and change the certain font shortcut keys
> 
> ![img](https://user-images.githubusercontent.com/17852229/54696239-299c4300-4b34-11e9-8eb7-edaba7de6442.png)

Thank you!

**Comment by keremciu** [comment]
perfect thanks for sharing @mamuts12 

I couldn't find a place to put this functionality for bundle installation but if you import single svg iconfont then there's an input to write your shortcut

I'm happy to hear your problem is gone! :)
