### ISSUE TITLE
problem about search

### ISSUE THREAD

**Issue by leon0407** [keremciu/sketch-iconfont#48]
I want to search a fontawsome name, but it doesn't make it. because the icons are named as something like icon100. I want to know how to deal with it .thank you !

![8c62c5e5-aafd-424e-8a37-7f02f6c8650d](https://cloud.githubusercontent.com/assets/7954078/14662099/a53fc0ae-06e5-11e6-91dd-f4bea6d45743.png)

**Comment by keremciu** [comment]
Hello @leon0407 

I can't change it because svg font of fontawesome doesn't have any glyph name, https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/fonts/fontawesome-webfont.svg

normally fonts have glyph names, you can compare it with svg font of material icons

https://raw.githubusercontent.com/google/material-design-icons/master/iconfont/MaterialIcons-Regular.svg

but yes, I created an issue for this

https://github.com/FortAwesome/Font-Awesome/issues/9080
