### ISSUE TITLE
Google Material Design Icons

### ISSUE THREAD

**Issue by espman** [keremciu/sketch-iconfont#68]
Hi Kerem,

first of all thanks a lot for the amazing plugin, I really love It.

After installing the plugin and the font bundle, the icon-font on the Google Material Design Website are not loading correctly anymore. Uninstalling the plugin does not fix the problem.
Do you think this could be related to the plugin?

Cheers Manuel
![screenshot](https://cloud.githubusercontent.com/assets/20412454/17840165/7eff1542-6852-11e6-975d-002f6f4b7659.png)

**Comment by keremciu** [comment]
Hello @espman

Yea, what a mistake sorry about that, I'll try to fix that soon

Cheers,
Kerem

**Comment by espman** [comment]
Thanks so much for looking into this.
Love your plugin, great work!

**Comment by jwandrews** [comment]
Since updating to v4.4.0 of the plugin, my install of MaterialIcons-Regular has not been able to add an icon properly. I've tried reinstalling the font from the font-bundle repo, from Google itself. I've also tried reinstalling the plugin (both from Sketch Toolbox and manually). I have tried removing and reinstalling the default font bundle from the font-bundle repo. To no avail. 

When I try adding any of the icons from Material Icons, they insert with the outlined question mark icon. In the font panel, it is showing as ".LastResort" font. If I manually switch it to "Material Icons", the icon displays properly.

Attached is a screenshot of what the Material Icons grid insert looks like.

![material-icon-grid-insert-broken](https://cloud.githubusercontent.com/assets/7916874/18055105/acbe950c-6dd4-11e6-9fe7-bf56ca53e0d3.png)

I'd be happy to help debug further. Just not sure what info you may need.

**Comment by keremciu** [comment]
@jwandrews Hello Jeff, you're right, I've failed to update material icons because of their choice. They did not change the font generator, thats the main problem :/

But I think you should to install materialicons font from Font-Bundle repo. When you downlaod the repo, it has "ttf" directory, you can find the working material icon font there. I'll be update that soon but you should install ttf files like that

**Comment by jwandrews** [comment]
Ok so, install font from font-bundle repo, and it should work..

If there's anything I can do to help, let me know.

Thanks!

**Comment by khornberg** [comment]
I am running into this as well.

If I install the `materialicons-regular.ttf` from the `font-bundles` repo, the icon font in sketch works but breaks any web page that uses Material Icons in a browser (tested in Chrome and Safari).

If I install the `ttf` from https://github.com/google/material-design-icons/tree/master/iconfont, web pages show up correctly but the iconfont does not work in sketch.

**Comment by keremciu** [comment]
@khornberg yep, you got the same problem, I really hate this too :D really sorry about it, I will fix material icon font this weekend

**Comment by LinkCable** [comment]
also running into the same issue

**Comment by jamiebeech** [comment]
Same issue here. Even deleting the plugin doesn't fix the issue. Any way of fixing the issue that the plugin has caused rather than the plugin itself?

**Comment by jwandrews** [comment]
@jamiebeech if you are only worried about solving the font issue and ok with not using the plugin until it's fixed, you should be able to uninstall the font-bundle version of the material icons font and installing the most recent version of the font from this repo: https://github.com/google/material-design-icons

**Comment by jamiebeech** [comment]
Thanks for the swift reply. I will continue to use the plugin I just needed the icon font to work for other projects in the meantime.

**Comment by jwandrews** [comment]
@keremciu any idea when this fix will be released? looking to use this plugin again but need those Material Icons. Thanks!

**Comment by keremciu** [comment]
@jwandrews @LinkCable @jamiebeech Hey guys, I've updated font bundle, you should remove "materialicons" font from Font Book application on your macosx. Install new ttf file from font-bundle folder "material.ttf" and you should install new font-bundle from the repo.

I've tried to find a good way but it is not working what I have believe before. You can see material icons on web now. By the way sorry again about this problem :/ I was so busy thats why I could not fixed before this problem. hereafter, I will be so careful

**Comment by khornberg** [comment]
Works well, thanks

**Comment by jwandrews** [comment]
Thank you so much.
Works great! Keep up the good work.

**Comment by espman** [comment]
That is so cool! Thanks so much, works perfect.

**Comment by keremciu** [comment]
I've another plugin to update your fonts to the new file of material icons

[font-fixer.zip](https://github.com/keremciu/sketch-iconfont/files/580194/font-fixer.zip)

**Comment by senemuzuner** [comment]
Hi, I have the same problem. Material icons font looks empty when I open it in the fonts. I have a huge collection of design works from the previous designer used with your plugin it seems but they all look as meaningless characters and when I choose the font to correct them they turn to question marks.

If I don't fix this I'll have to put all those icons from scratch '(
